-- Task B: per-workshop special-offer links. Admin creates an offer
-- (discount + optional expiry + max-uses cap) and gets a shareable
-- ?offer=<token> URL. The token is the access secret; RLS is
-- admin-only at the table level, anon access goes through the
-- get_workshop_offer / claim_workshop_offer SECURITY DEFINER RPCs.

-- ── 1. workshop_offers table ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS workshop_offers (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  workshop_id    uuid        NOT NULL REFERENCES workshops(id) ON DELETE CASCADE,
  -- URL secret — generated by DB so the client never picks the value.
  -- uuid (matches production); the ?offer=<token> param is a uuid string.
  token          uuid        UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  -- Internal admin label (not shown to the customer).
  label          text        NOT NULL,
  discount_type  text        NOT NULL CHECK (discount_type IN ('fixed', 'percent')),
  -- fixed → the special price itself (₪); percent → % off.
  discount_value numeric     NOT NULL CHECK (discount_value >= 0),
  -- Override payment link required when discount_value > 0.
  payment_link   text,
  max_uses       int         CHECK (max_uses IS NULL OR max_uses > 0),
  uses_count     int         NOT NULL DEFAULT 0,
  expires_at     timestamptz,
  is_active      boolean     NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_workshop_offers_workshop
  ON workshop_offers (workshop_id)
  WHERE is_active;

CREATE UNIQUE INDEX IF NOT EXISTS idx_workshop_offers_token
  ON workshop_offers (token);

-- ── 2. Attach offer columns to registration_leads ────────────────

ALTER TABLE registration_leads
  ADD COLUMN IF NOT EXISTS offer_id    uuid REFERENCES workshop_offers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS offer_token uuid;

-- ── 3. RLS — admin full CRUD, no direct public access ────────────

ALTER TABLE workshop_offers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins read workshop offers"   ON workshop_offers;
CREATE POLICY "admins read workshop offers"
  ON workshop_offers FOR SELECT
  TO authenticated
  USING (EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND is_admin = true));

DROP POLICY IF EXISTS "admins insert workshop offers" ON workshop_offers;
CREATE POLICY "admins insert workshop offers"
  ON workshop_offers FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND is_admin = true));

DROP POLICY IF EXISTS "admins update workshop offers" ON workshop_offers;
CREATE POLICY "admins update workshop offers"
  ON workshop_offers FOR UPDATE
  TO authenticated
  USING  (EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND is_admin = true));

DROP POLICY IF EXISTS "admins delete workshop offers" ON workshop_offers;
CREATE POLICY "admins delete workshop offers"
  ON workshop_offers FOR DELETE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND is_admin = true));

-- ── 4. get_workshop_offer(p_token) ───────────────────────────────
-- Public read path for the ?offer=<token> landing page. Returns the
-- raw offer row so the client can decide whether it's still
-- claimable (expired / maxed / inactive checks happen in JS, not
-- here, to keep the RPC simple). SECURITY DEFINER so anon callers
-- can read the row without a table-level SELECT grant.

CREATE OR REPLACE FUNCTION get_workshop_offer(p_token uuid)
RETURNS SETOF workshop_offers
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT * FROM workshop_offers WHERE token = p_token LIMIT 1;
$$;

-- ── 5. claim_workshop_offer(p_token) ─────────────────────────────
-- Atomic claim: locks the row, verifies it is still redeemable, and
-- increments uses_count in a single UPDATE. Returns the updated row
-- on success, or NULL if the offer is no longer claimable (expired,
-- maxed, inactive, or not found). Concurrent claims are serialised
-- by the SELECT … FOR UPDATE lock so the uses_count cap is
-- race-safe.

CREATE OR REPLACE FUNCTION claim_workshop_offer(p_token uuid)
RETURNS SETOF workshop_offers
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_offer workshop_offers;
BEGIN
  -- Lock the row so concurrent callers queue up here.
  SELECT * INTO v_offer
    FROM workshop_offers
   WHERE token = p_token
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN;   -- offer doesn't exist → return empty set (NULL to JS)
  END IF;

  -- Reject if no longer claimable.
  IF NOT v_offer.is_active
     OR (v_offer.expires_at IS NOT NULL AND v_offer.expires_at <= now())
     OR (v_offer.max_uses   IS NOT NULL AND v_offer.uses_count >= v_offer.max_uses)
  THEN
    RETURN;   -- expired / maxed / disabled → return empty set
  END IF;

  -- Claim: bump the counter and return the updated row.
  UPDATE workshop_offers
     SET uses_count = uses_count + 1
   WHERE id = v_offer.id
  RETURNING * INTO v_offer;

  RETURN NEXT v_offer;
END;
$$;
