-- Update Registration form with full fields
INSERT INTO forms (id, title, description, fields_json, is_active)
VALUES (
  'a1000000-0000-0000-0000-000000000001',
  'טופס הרשמה',
  'ברוכה הבאה! נשמח לדעת קצת עליך לפני שנתחיל 🌿',
  '[
    {"id":"f1","type":"text",   "label":"שם פרטי",                                "required":true},
    {"id":"f2","type":"text",   "label":"שם משפחה",                               "required":true},
    {"id":"f3","type":"text",   "label":"מספר טלפון",                             "required":true},
    {"id":"f4","type":"text",   "label":"כתובת מייל",                             "required":true},
    {"id":"f5","type":"select", "label":"באיזה סדנה את מעוניינת?",               "required":true,
      "options":["סדנאות ליווי התפתחותי - עטופים","סדנאות עיסוי תינוקות"]},
    {"id":"f6","type":"select", "label":"אני מאשרת תשלום ע״ס 290 ש״ח עבור הסדנה","required":true,
      "options":["אני מאשרת"]}
  ]'::jsonb,
  true
)
ON CONFLICT (id) DO UPDATE
  SET title       = EXCLUDED.title,
      description = EXCLUDED.description,
      fields_json = EXCLUDED.fields_json,
      is_active   = EXCLUDED.is_active;

-- Full ליווי אחרי לידה / ליווי פרטני form
INSERT INTO forms (id, title, description, fields_json, is_active)
VALUES (
  'a1000000-0000-0000-0000-000000000003',
  'ליווי אחרי לידה - MIMO',
  'שאלון מעקב לאחר לידה — יש למלא בתיאום עם ברנדה',
  '[
    {"id":"f1", "type":"text",     "label":"תאריך מילוי השאלון",                                                                                           "required":true},
    {"id":"f2", "type":"text",     "label":"שם פרטי של האם",                                                                                               "required":true},
    {"id":"f3", "type":"text",     "label":"שם משפחה של האם",                                                                                              "required":true},
    {"id":"f4", "type":"text",     "label":"טלפון נייד",                                                                                                   "required":true},
    {"id":"f5", "type":"text",     "label":"כתובת מייל",                                                                                                   "required":true},
    {"id":"f6", "type":"text",     "label":"תאריך לידה של האם",                                                                                            "required":false},
    {"id":"f7", "type":"text",     "label":"עיר מגורים",                                                                                                   "required":false},
    {"id":"f8", "type":"text",     "label":"עיסוק האם",                                                                                                    "required":false},
    {"id":"f9", "type":"textarea", "label":"מהי סיבת הפנייה?",                                                                                             "required":false},
    {"id":"f10","type":"text",     "label":"שם פרטי של האב",                                                                                               "required":false},
    {"id":"f11","type":"text",     "label":"שם משפחה של האב",                                                                                              "required":false},
    {"id":"f12","type":"text",     "label":"עיסוק האב",                                                                                                    "required":false},
    {"id":"f13","type":"text",     "label":"שם פרטי של התינוק/ת",                                                                                          "required":false},
    {"id":"f14","type":"text",     "label":"שם משפחה של התינוק/ת",                                                                                         "required":false},
    {"id":"f15","type":"text",     "label":"תאריך לידה של התינוק/ת",                                                                                       "required":false},
    {"id":"f16","type":"text",     "label":"גיל",                                                                                                          "required":false},
    {"id":"f17","type":"text",     "label":"גיל מתוקן (לפגים)",                                                                                            "required":false},
    {"id":"f18","type":"text",     "label":"משקל לידה",                                                                                                    "required":false},
    {"id":"f19","type":"text",     "label":"שבוע לידה",                                                                                                    "required":false},
    {"id":"f20","type":"select",   "label":"מין",                                                                                                          "required":false,
      "options":["זכר","נקבה"]},
    {"id":"f21","type":"text",     "label":"מנח העובר ברחם",                                                                                               "required":false},
    {"id":"f22","type":"textarea", "label":"מה היה מהלך ההריון? (האם היה מתוכנן / האם היו מצבי לחץ / האם היה אירוע חריג...)",                             "required":false},
    {"id":"f23","type":"textarea", "label":"מה היה מהלך הלידה? (הלידה עצמה וקשיים או בהתארגנות לאחריה)",                                                 "required":false},
    {"id":"f24","type":"textarea", "label":"תארי את תחושותייך בתקופה הראשונה לאחר הלידה והחזרה הביתה",                                                    "required":false},
    {"id":"f25","type":"textarea", "label":"תארי את ילדך בשבועות הראשונים שלאחר הלידה (פעיל / שקט / מובן או לא מובן...)",                                 "required":false},
    {"id":"f26","type":"textarea", "label":"תארי את ילדך כיום (העדפות, תכונות אופי מיוחדים ודברים מאישיותו)",                                             "required":false},
    {"id":"f27","type":"text",     "label":"עם מי התינוק/ת מבלה את רוב שעות היום?",                                                                       "required":false},
    {"id":"f28","type":"select",   "label":"איך התינוק ניזון?",                                                                                            "required":false,
      "options":["הנקה","בקבוק","שילוב"]},
    {"id":"f29","type":"text",     "label":"בזמן עירות נמצא על",                                                                                           "required":false},
    {"id":"f30","type":"textarea", "label":"האם משתתף בפעילויות או חוגים נוספים? אם כן, אילו?",                                                           "required":false},
    {"id":"f31","type":"textarea", "label":"כיצד נרגע (על הידיים, מוצץ, תנועה ועוד):",                                                                    "required":false},
    {"id":"f32","type":"textarea", "label":"כיצד אתם נושאים אותו לאורך היום (אוהב להתערסל, על הכתף, מנשא וכו׳):",                                        "required":false},
    {"id":"f33","type":"textarea", "label":"האם נרתע/נמנע ממגע באזורים שונים בגוף? אם כן היכן?",                                                         "required":false},
    {"id":"f34","type":"textarea", "label":"האם נרתע ממגע בדרקמים שונים כמו סוגי אוכל, דשא, חול, לכלוך?",                                               "required":false},
    {"id":"f35","type":"textarea", "label":"האם נרתע מרעשים? עוצמות קול? אם כן, אילו?",                                                                   "required":false},
    {"id":"f36","type":"textarea", "label":"תארי את שיגרת השינה ביום (איך נרדם? לכמה זמן? באיזה מנח ישן?)",                                              "required":false},
    {"id":"f37","type":"textarea", "label":"תארי את שיגרת השינה בלילה (איך נרדם? לכמה זמן? באיזה מנח ישן?)",                                             "required":false},
    {"id":"f38","type":"textarea", "label":"משהו נוסף שתרצי שאדע?",                                                                                       "required":false},
    {"id":"f39","type":"select",   "label":"הצהרת בריאות: אני מאשרת כי המידע שמסרתי נכון ומדויק",                                                         "required":true,
      "options":["אני מאשרת"]},
    {"id":"f40","type":"textarea", "label":"האם ידוע על בעיה בריאותית או התפתחותית כלשהי? אם כן, פרטי.",                                                 "required":false},
    {"id":"f41","type":"select",   "label":"האם סובל/ת מגזים, רפלוקס או בעיות עיכול?",                                                                    "required":false,
      "options":["כן","לא"]},
    {"id":"f42","type":"textarea", "label":"אם כן — פרטי (גזים / רפלוקס / עיכול)",                                                                        "required":false},
    {"id":"f43","type":"textarea", "label":"האם התינוק/ת נוטל/ת תרופות באופן קבוע?",                                                                      "required":false},
    {"id":"f44","type":"textarea", "label":"האם עבר בדיקות רפואיות מאז הלידה (בדיקת שמיעה / בירור נוירולוגי / מעקב גדילה...)",                          "required":false},
    {"id":"f45","type":"select",   "label":"האם אושפז בבית חולים?",                                                                                       "required":false,
      "options":["כן","לא"]},
    {"id":"f46","type":"textarea", "label":"אם כן — פרטי (אשפוז)",                                                                                        "required":false},
    {"id":"f47","type":"textarea", "label":"האם עבר טיפולים נוספים? אם כן, פרטי.",                                                                        "required":false},
    {"id":"f48","type":"select",   "label":"במהלך המפגש יצולמו תמונות וסרטונים לצורך תיעוד מקצועי. האם את מאשרת?",                                       "required":true,
      "options":["כן, אני מאשרת","לא, אני לא מאשרת"]},
    {"id":"f49","type":"text",     "label":"איך שמעת על מימו?",                                                                                            "required":false}
  ]'::jsonb,
  true
)
ON CONFLICT (id) DO UPDATE
  SET title       = EXCLUDED.title,
      description = EXCLUDED.description,
      fields_json = EXCLUDED.fields_json,
      is_active   = EXCLUDED.is_active;

-- שאלון התפתחות — identical content to ליווי אחרי לידה
INSERT INTO forms (id, title, description, fields_json, is_active)
VALUES (
  'a1000000-0000-0000-0000-000000000004',
  'שאלון התפתחות - MIMO',
  'שאלון מעקב התפתחותי — יש למלא בתיאום עם ברנדה',
  '[
    {"id":"f1", "type":"text",     "label":"תאריך מילוי השאלון",                                                                                           "required":true},
    {"id":"f2", "type":"text",     "label":"שם פרטי של האם",                                                                                               "required":true},
    {"id":"f3", "type":"text",     "label":"שם משפחה של האם",                                                                                              "required":true},
    {"id":"f4", "type":"text",     "label":"טלפון נייד",                                                                                                   "required":true},
    {"id":"f5", "type":"text",     "label":"כתובת מייל",                                                                                                   "required":true},
    {"id":"f6", "type":"text",     "label":"תאריך לידה של האם",                                                                                            "required":false},
    {"id":"f7", "type":"text",     "label":"עיר מגורים",                                                                                                   "required":false},
    {"id":"f8", "type":"text",     "label":"עיסוק האם",                                                                                                    "required":false},
    {"id":"f9", "type":"textarea", "label":"מהי סיבת הפנייה?",                                                                                             "required":false},
    {"id":"f10","type":"text",     "label":"שם פרטי של האב",                                                                                               "required":false},
    {"id":"f11","type":"text",     "label":"שם משפחה של האב",                                                                                              "required":false},
    {"id":"f12","type":"text",     "label":"עיסוק האב",                                                                                                    "required":false},
    {"id":"f13","type":"text",     "label":"שם פרטי של התינוק/ת",                                                                                          "required":false},
    {"id":"f14","type":"text",     "label":"שם משפחה של התינוק/ת",                                                                                         "required":false},
    {"id":"f15","type":"text",     "label":"תאריך לידה של התינוק/ת",                                                                                       "required":false},
    {"id":"f16","type":"text",     "label":"גיל",                                                                                                          "required":false},
    {"id":"f17","type":"text",     "label":"גיל מתוקן (לפגים)",                                                                                            "required":false},
    {"id":"f18","type":"text",     "label":"משקל לידה",                                                                                                    "required":false},
    {"id":"f19","type":"text",     "label":"שבוע לידה",                                                                                                    "required":false},
    {"id":"f20","type":"select",   "label":"מין",                                                                                                          "required":false,
      "options":["זכר","נקבה"]},
    {"id":"f21","type":"text",     "label":"מנח העובר ברחם",                                                                                               "required":false},
    {"id":"f22","type":"textarea", "label":"מה היה מהלך ההריון? (האם היה מתוכנן / האם היו מצבי לחץ / האם היה אירוע חריג...)",                             "required":false},
    {"id":"f23","type":"textarea", "label":"מה היה מהלך הלידה? (הלידה עצמה וקשיים או בהתארגנות לאחריה)",                                                 "required":false},
    {"id":"f24","type":"textarea", "label":"תארי את תחושותייך בתקופה הראשונה לאחר הלידה והחזרה הביתה",                                                    "required":false},
    {"id":"f25","type":"textarea", "label":"תארי את ילדך בשבועות הראשונים שלאחר הלידה (פעיל / שקט / מובן או לא מובן...)",                                 "required":false},
    {"id":"f26","type":"textarea", "label":"תארי את ילדך כיום (העדפות, תכונות אופי מיוחדים ודברים מאישיותו)",                                             "required":false},
    {"id":"f27","type":"text",     "label":"עם מי התינוק/ת מבלה את רוב שעות היום?",                                                                       "required":false},
    {"id":"f28","type":"select",   "label":"איך התינוק ניזון?",                                                                                            "required":false,
      "options":["הנקה","בקבוק","שילוב"]},
    {"id":"f29","type":"text",     "label":"בזמן עירות נמצא על",                                                                                           "required":false},
    {"id":"f30","type":"textarea", "label":"האם משתתף בפעילויות או חוגים נוספים? אם כן, אילו?",                                                           "required":false},
    {"id":"f31","type":"textarea", "label":"כיצד נרגע (על הידיים, מוצץ, תנועה ועוד):",                                                                    "required":false},
    {"id":"f32","type":"textarea", "label":"כיצד אתם נושאים אותו לאורך היום (אוהב להתערסל, על הכתף, מנשא וכו׳):",                                        "required":false},
    {"id":"f33","type":"textarea", "label":"האם נרתע/נמנע ממגע באזורים שונים בגוף? אם כן היכן?",                                                         "required":false},
    {"id":"f34","type":"textarea", "label":"האם נרתע ממגע בדרקמים שונים כמו סוגי אוכל, דשא, חול, לכלוך?",                                               "required":false},
    {"id":"f35","type":"textarea", "label":"האם נרתע מרעשים? עוצמות קול? אם כן, אילו?",                                                                   "required":false},
    {"id":"f36","type":"textarea", "label":"תארי את שיגרת השינה ביום (איך נרדם? לכמה זמן? באיזה מנח ישן?)",                                              "required":false},
    {"id":"f37","type":"textarea", "label":"תארי את שיגרת השינה בלילה (איך נרדם? לכמה זמן? באיזה מנח ישן?)",                                             "required":false},
    {"id":"f38","type":"textarea", "label":"משהו נוסף שתרצי שאדע?",                                                                                       "required":false},
    {"id":"f39","type":"select",   "label":"הצהרת בריאות: אני מאשרת כי המידע שמסרתי נכון ומדויק",                                                         "required":true,
      "options":["אני מאשרת"]},
    {"id":"f40","type":"textarea", "label":"האם ידוע על בעיה בריאותית או התפתחותית כלשהי? אם כן, פרטי.",                                                 "required":false},
    {"id":"f41","type":"select",   "label":"האם סובל/ת מגזים, רפלוקס או בעיות עיכול?",                                                                    "required":false,
      "options":["כן","לא"]},
    {"id":"f42","type":"textarea", "label":"אם כן — פרטי (גזים / רפלוקס / עיכול)",                                                                        "required":false},
    {"id":"f43","type":"textarea", "label":"האם התינוק/ת נוטל/ת תרופות באופן קבוע?",                                                                      "required":false},
    {"id":"f44","type":"textarea", "label":"האם עבר בדיקות רפואיות מאז הלידה (בדיקת שמיעה / בירור נוירולוגי / מעקב גדילה...)",                          "required":false},
    {"id":"f45","type":"select",   "label":"האם אושפז בבית חולים?",                                                                                       "required":false,
      "options":["כן","לא"]},
    {"id":"f46","type":"textarea", "label":"אם כן — פרטי (אשפוז)",                                                                                        "required":false},
    {"id":"f47","type":"textarea", "label":"האם עבר טיפולים נוספים? אם כן, פרטי.",                                                                        "required":false},
    {"id":"f48","type":"select",   "label":"במהלך המפגש יצולמו תמונות וסרטונים לצורך תיעוד מקצועי. האם את מאשרת?",                                       "required":true,
      "options":["כן, אני מאשרת","לא, אני לא מאשרת"]},
    {"id":"f49","type":"text",     "label":"איך שמעת על מימו?",                                                                                            "required":false}
  ]'::jsonb,
  true
)
ON CONFLICT (id) DO UPDATE
  SET title       = EXCLUDED.title,
      description = EXCLUDED.description,
      fields_json = EXCLUDED.fields_json,
      is_active   = EXCLUDED.is_active;
